### ISSUE TITLE
How to delete an aircraft from standing data?

### ISSUE THREAD

**Issue by TencentSZ** [vradarserver/standing-data#3]
I found one piece of record where  ICAO=791298 is incorrect and the right one of which ICAO is 781298 already exists, so I decided to delete the incorrect one. Then I was confused by the user interface when I try to edit an aircraft batch. If I click on the red 'X' button on the right of the list, does it mean removing a pending record from this batch, or does it delete a piece of aircraft record from the standing data database?

**Comment by vradarserver** [comment]
When you add a record to a batch you need to specify at that point whether you are adding a new ICAO, updating an existing ICAO or deleting an existing ICAO. That is the only place where you can say that you want to delete an ICAO from the database.

The icons you see against each record in the batch are to edit the record, or to delete the record.
